### ISSUE TITLE
Incompatibility with apispec 1.0.0

### ISSUE THREAD

**Issue by bbc2** [brunoais/apispec-decorated-crawler#4]
Since [1.0.0b1](https://github.com/marshmallow-code/apispec/blob/dev/CHANGELOG.rst#100b1-2018-07-29), apispec has removed the `Path` class, which this package uses.

**Comment by brunoais** [comment]
Thank you, @bbc2 .
Are you available to work with @leamingrad to improve this project?
I'm quite tight in time for the next few months
